name: ZNPCsPlus
main: lol.pyr.znpcsplus.ZNPCsPlus
load: POSTWORLD
version: ${version}
api-version: 1.13
softdepend:
  - PlaceholderAPI
  - ServersNPC
  - ProtocolLib
  - ProtocolSupport
  - ViaVersion
  - ViaBackwards
  - ViaRewind
  - Geyser-Spigot
authors: [gonalez, Pyr]